# Generated by Django 2.0.2 on 2018-02-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('state', models.CharField(max_length=2, verbose_name='State')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('zip', models.CharField(max_length=10, verbose_name='Zip')),
                ('building_code', models.CharField(max_length=20, verbose_name='Building Code')),
                ('building_description', models.CharField(max_length=100, verbose_name='Building Description')),
                ('building_name', models.CharField(max_length=100, verbose_name='Building Name')),
                ('building_number', models.CharField(max_length=20, verbose_name='Building Number')),
                ('building_abbr', models.CharField(max_length=3, verbose_name='Building Abbreviation')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('update_date', models.DateTimeField(verbose_name='last update')),
            ],
            options={
                'ordering': ('building_name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.CharField(max_length=100, verbose_name='CRN')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('course_number', models.CharField(max_length=100, verbose_name='Course Number')),
                ('section', models.CharField(max_length=100, verbose_name='Section')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('term', models.CharField(max_length=100, verbose_name='Term')),
                ('year', models.CharField(max_length=100, verbose_name='Year')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('description_prereqs', models.TextField(max_length=200, verbose_name='Description with Prereqs')),
                ('prerequisites', models.TextField(max_length=100, verbose_name='Prerequisites')),
                ('instructor', models.CharField(max_length=100, verbose_name='Instructor')),
                ('credit_hours', models.IntegerField(max_length=100, verbose_name='Credit Hours')),
                ('room', models.CharField(max_length=100, verbose_name='Room')),
                ('days', models.CharField(max_length=100, verbose_name='Days')),
                ('begin_time', models.CharField(max_length=100, verbose_name='Begin Time')),
                ('end_time', models.CharField(max_length=100, verbose_name='End Time')),
                ('max_enroll', models.IntegerField(verbose_name='Max Enroll')),
                ('actual_enroll', models.IntegerField(verbose_name='Actual Enroll')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QA.Building')),
            ],
            options={
                'ordering': ('subject', 'course_number'),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=20, verbose_name='Department ID')),
                ('parent_department_id', models.CharField(max_length=20, verbose_name='Parent Department ID')),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('descriptions', models.CharField(max_length=300, null=True, verbose_name='Department Descriptions')),
                ('contact_phone_international_code', models.CharField(max_length=5, verbose_name='International Code')),
                ('contact_phone_area_code', models.CharField(max_length=3, verbose_name='Area Code')),
                ('contact_phone_number', models.CharField(max_length=7, verbose_name='Number')),
                ('contact_phone_extension', models.CharField(max_length=10, verbose_name='Extension')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_facebook', models.URLField(verbose_name='Facebook')),
                ('contact_website', models.URLField(verbose_name='Website')),
                ('update_date', models.DateTimeField(verbose_name='last update')),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QA.Building')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=100, verbose_name='Supervisor')),
                ('supervisee', models.CharField(max_length=100, verbose_name='Supervisee')),
                ('tracks', models.CharField(max_length=20, verbose_name='Tracks Account')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('middle_name', models.CharField(max_length=100, null=True, verbose_name='Middle Name')),
                ('prefix_name', models.CharField(max_length=100, null=True, verbose_name='Prefix')),
                ('suffix_name', models.CharField(max_length=100, null=True, verbose_name='Suffix')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_international_code', models.CharField(max_length=5, verbose_name='International Code')),
                ('phone_area_code', models.CharField(max_length=3, verbose_name='Area Code')),
                ('phone_number', models.CharField(max_length=7, verbose_name='Number')),
                ('phone_extension', models.CharField(max_length=10, verbose_name='Extension')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('position', models.CharField(max_length=100, verbose_name='Position (Primary and Additional) JSON')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QA.Department')),
            ],
            options={
                'ordering': ('tracks',),
            },
        ),
    ]
