# Generated by Django 2.0.2 on 2018-03-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0002_auto_20180226_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('question_vector', models.TextField(verbose_name='Question Vector')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'ordering': ('question_vector', 'question'),
            },
        ),
    ]
