# Generated by Django 2.0.2 on 2018-03-17 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0003_questionanswerpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 16, 53, 27, 852256, tzinfo=utc), verbose_name='last update'),
        ),
        migrations.AddField(
            model_name='employee',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 16, 53, 27, 851401, tzinfo=utc), verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='building',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 16, 53, 27, 849991, tzinfo=utc), verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='course',
            name='building',
            field=models.CharField(default='TBA', max_length=100, verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='department',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 16, 53, 27, 850672, tzinfo=utc), verbose_name='last update'),
        ),
    ]
