# Generated by Django 2.0.2 on 2018-03-17 16:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0005_auto_20180317_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='update_date',
            field=models.DateTimeField(verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='course',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 16, 55, 40, 871656, tzinfo=utc), verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='department',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 16, 55, 40, 870078, tzinfo=utc), verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 17, 16, 55, 40, 870841, tzinfo=utc), verbose_name='last update'),
        ),
    ]
