# Generated by Django 2.0.2 on 2018-03-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0006_auto_20180317_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='update_date',
            field=models.DateTimeField(verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='department',
            name='update_date',
            field=models.DateTimeField(verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='update_date',
            field=models.DateTimeField(verbose_name='last update'),
        ),
    ]
