# Generated by Django 2.0.2 on 2018-03-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0007_auto_20180317_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='building',
            field=models.TextField(default='TBA', verbose_name='Building'),
        ),
    ]
