# Generated by Django 2.0.2 on 2018-03-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0008_auto_20180317_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='building',
            field=models.TextField(default='NA', verbose_name='Building'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.TextField(default='NA', verbose_name='Department'),
        ),
    ]
