# Generated by Django 2.0.2 on 2018-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0009_auto_20180317_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_id',
            field=models.CharField(default='', max_length=20, verbose_name='Department ID'),
        ),
    ]
