# Generated by Django 2.0.2 on 2018-03-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0010_employee_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_extension',
            field=models.CharField(max_length=10, null=True, verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
