# Generated by Django 2.0.2 on 2018-03-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0011_auto_20180317_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='contact_phone_extension',
            field=models.CharField(max_length=10, null=True, verbose_name='Extension'),
        ),
    ]
