# Generated by Django 2.0.2 on 2018-03-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0013_auto_20180317_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='contact_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
