# Generated by Django 2.0.2 on 2018-03-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0017_auto_20180317_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='building',
            field=models.TextField(default='NA', null=True, verbose_name='Building'),
        ),
    ]
