# Generated by Django 2.0.2 on 2018-03-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0018_auto_20180317_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='contact_phone_area_code',
            field=models.CharField(max_length=3, null=True, verbose_name='Area Code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_area_code',
            field=models.CharField(max_length=3, null=True, verbose_name='Area Code'),
        ),
    ]
