# Generated by Django 2.0.2 on 2018-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0019_auto_20180317_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_international_code',
            field=models.CharField(max_length=5, null=True, verbose_name='International Code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=7, null=True, verbose_name='Number'),
        ),
    ]
