# Generated by Django 2.0.2 on 2018-03-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0021_auto_20180317_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='building',
            field=models.TextField(default='NA', null=True, verbose_name='Building JSON'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.TextField(default='NA', null=True, verbose_name='Department JSON'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.TextField(verbose_name='Position (Primary and Additional) JSON'),
        ),
    ]
