# Generated by Django 2.0.2 on 2018-03-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0022_auto_20180318_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word_Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.CharField(max_length=100, verbose_name='Original Word')),
                ('standard_word', models.CharField(max_length=100, verbose_name='Standard Word')),
            ],
            options={
                'ordering': ('standard_word', 'original_word'),
            },
        ),
    ]
