# Generated by Django 2.0.3 on 2018-04-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0024_pastquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastquestions',
            name='questions',
        ),
        migrations.AddField(
            model_name='pastquestions',
            name='questions',
            field=models.TextField(default='Where is Panther Dining Hall?', verbose_name='Question'),
            preserve_default=False,
        ),
    ]
