# Generated by Django 2.0.3 on 2018-04-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0025_auto_20180403_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PastQuestions',
            new_name='PastQuestion',
        ),
    ]
