# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskPete', '0002_auto_20171004_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_text',
            field=models.CharField(default='hello world', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
