# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskPete', '0003_auto_20171004_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRN', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=5)),
                ('credit', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=20)),
                ('enrolled', models.IntegerField()),
                ('limit', models.IntegerField()),
                ('semester', models.CharField(max_length=20)),
            ],
        ),
    ]
