# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AskPete', '0004_auto_20171126_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='isAddress',
            new_name='Is Address?',
        ),
    ]
