# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskPete', '0005_auto_20171126_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.IntegerField(max_length=5)),
                ('subject', models.CharField(max_length=8)),
                ('section', models.CharField(max_length=3)),
                ('credit', models.IntegerField(max_length=1)),
                ('instructor', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=11)),
                ('days', models.CharField(max_length=4)),
            ],
        ),
    ]
