# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskPete', '0006_courseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='credit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='crn',
            field=models.IntegerField(),
        ),
    ]
