# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 18:36
from __future__ import unicode_literals

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AskPete', '0008_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rental',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100),
        ),
    ]
